stages:
  - build
  - test
  - deploy
  - clean

install maven packages:
  stage: build
  script:
    - echo "This job compiles code."
    - 'mvn install -DskipTests'

deploy mvn packages:
  stage: deploy
  image: maven:3.6.3-jdk-11-slim
  script:
    - 'mvn -DskipTests $MAVEN_CLI_OPTS deploy -s ci_settings.xml'
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy docker images:
  stage: deploy
  image: maven:3.6.3-jdk-11-slim
  services:
    - docker:dind
  script:
    - "mvn -DskipTest spring-boot:build-image -DCI_REGISTRY=$CI_REGISTRY -DCI_REGISTRY_USER=$CI_REGISTRY_USER -DCI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD -Dspring-boot.build-image.imageName=com.microservices/twitter.to.kafka.service:0.0.1-SNAPSHOT -Dspring-boot.build-image.publish=true"
    - "mvn -DskipTest spring-boot:build-image -DCI_REGISTRY=$CI_REGISTRY -DCI_REGISTRY_USER=$CI_REGISTRY_USER -DCI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD -Dspring-boot.build-image.imageName=com.microservices/config.server:0.0.1-SNAPSHOT-Dspring-boot.build-image.publish=true"
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

clean mvn:
  stage: clean
  image: maven:3.6.3-jdk-11-slim
  script:
    - 'mvn clean'
