stages:
  - build
  - test
  - deploy
  - clean

install maven packages:
  stage: build
  script:
    - echo "This job compiles code."
    - 'mvn install -DskipTests'

deploy mvn packages:
  stage: deploy
  image: maven:3.6.3-jdk-11-slim
  script:
    - 'mvn -DskipTests $MAVEN_CLI_OPTS deploy -s ci_settings.xml'
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy docker images:
  stage: deploy
  image: maven:3.6.3-jdk-11-slim
  services:
    - docker:dind
  script:
    - mvn install -DskipTests
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

clean mvn:
  stage: clean
  image: maven:3.6.3-jdk-11-slim
  script:
    - 'mvn clean'
