variables:
  JAVA_HOME: "$JAVA_11_HOME"
image: busybox:latest
cache:
  paths:
    - ".m2/repository"
build1:
  stage: build
  script:
    - echo "Do your build here"
  except:
    variables:
      - "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
deploy:jdk11:
  stage: deploy
  script:
    - mvn deploy -s ci_settings.xml
  only:
    variables:
      - "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

