stages:
  - build
  - deploy
  - clean

install maven packages:
  stage: build
  script:
    - echo "This job compiles code."
    - mvn install -DskipTests

deploy mvn packages:
  stage: deploy
  script:
    - mvn -DskipTests $MAVEN_CLI_OPTS deploy -s ci_settings.xml
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

clean mvn:
  stage: clean
  script:
    - 'mvn clean'