variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true
    -DdeployAtEnd=true"
  JAVA_HOME: "$JAVA_11_HOME"
before_script:
  - echo "Before script section"
image: maven:3.8.2-jdk-11-slim
cache:
  paths:
    - ".m2/repository"
".verify":
  stage: test
  script:
    - echo "Starting installing Dependencies"
    - mvn install -DskipTests
  except:
    variables:
      - "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
verify:jdk11:
  stage: test
  script:
    - mvn install -DskipTests
  except:
    variables:
      - "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
deploy:
  image: maven:3.6-jdk-11
  script:
    - echo "Deploying dependencies"
    - mvn deploy -s ci_settings.xml -DskipTests
  only:
    - main
after_script:
  - echo "After script section"
  - mvn clean
Run Compose:
  image: ubuntu:latest
  script:
    - echo "Run script with $DEPLOY_VARIABLE as an argument"
    - cd Docker/
    - docker-compose up -d