stages:
  - build
  - test
  - deploy
  - clean

#install maven packages:
#  stage: build
#  script:
#    - echo "This job compiles code."
#    - mvn install -DskipTests
#
#deploy mvn packages:
#  stage: deploy
#  image: maven:3.6.3-jdk-11-slim
#  script:
#    - mvn -DskipTests $MAVEN_CLI_OPTS deploy -s ci_settings.xml
#  only:
#    variables:
#      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy docker images:
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - cd config-server
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"

  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

clean mvn:
  stage: clean
  image: maven:3.6.3-jdk-11-slim
  script:
    - 'mvn clean'
