docker image job:
  stage: Build
  image: maven:3.6.3-jdk-11-slim
  services:
    - docker:dind
  script:
    - echo "java.runtime.version=11" > system.properties
    - mvn spring-boot:build-image -DCI_REGISTRY=$CI_REGISTRY -DCI_REGISTRY_USER=$CI_REGISTRY_USER -DCI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD -Dspring-boot.build-image.imageName=SpringBootImage_${CI_JOB_ID} -Dspring-boot.build-image.publish=true
