twitter-to-kafka-service:
  twitter-keywords:
    - Elon Musk
    - crypto
    - ethereum
    - binance
  welcome-message: Hello microservices!
  enable-mock-tweets: false
  mock-min-tweet-length: 15
  mock-max-tweet-length: 15
  mock-sleep-ms : 1000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 1000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topin-name: twitter-topic
  topin-name-to-create:
    - twitter-topic
  num-of-partitions: 3
  replication-factor: 3


