twitter-to-kafka-service:
  twitter-keywords:
    - Elon Musk
    - crypto
    - ethereum
    - binance
  welcome-message: Hello microservices!
  enable-mock-tweets: false
  mock-min-tweet-length: 15
  mock-max-tweet-length: 15
  mock-sleep-ms : 1000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 1000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000
