twitter-to-kafka-service:
  twitter-keywords:
    - Elon Musk
    - crypto
    - ethereum
    - binance
  welcome-message: Hello microservices!
  enable-mock-tweets: true
  mock-min-tweet-length: 15
  mock-max-tweet-length: 15
  mock-sleep-ms : 1000
