name: Build application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build Kafka Infrastructure
        run: docker-compose -f Docker/kafka_cluster.yml up -d
        env:
          KAFKA_VERSION: 5.0.4
          ELASTIC_VERSION: 7.9.1
          SERVICE_VERSION: 0.0.1-SNAPSHOT
          GLOBAL_NETWORK: application
          GROUP_ID: com.microservices
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Application
        run: mvn -B package --file pom.xml

